Display individual employers: Last test case was not passing and presented the following preplexing error:
  AssertionError: `execute_sql` has not been called or has the wrong parameters.

After hours I realized this was due to case-sensitivity in the where clause.
The following statement:

    execute_sql('SELECT * FROM employer where id=?', [employer_id], single=True)

should have been

    execute_sql('SELECT * FROM employer WHERE id=?', [employer_id], single=True)

'where' needed to be 'WHERE'!!